let GAOKAO_VOCABULARY = [
  { word: "abandon", meaning: "v. 放弃；遗弃" },
  { word: "ability", meaning: "n. 能力；才能" },
  { word: "absorb", meaning: "v. 吸收；理解；使专心" },
  { word: "access", meaning: "n. 通道；使用权 v. 获取" },
  { word: "accompany", meaning: "v. 陪伴；伴随" },
  { word: "accomplish", meaning: "v. 完成；实现" },
  { word: "account", meaning: "n. 账户；描述；解释" },
  { word: "accurate", meaning: "adj. 准确的；精确的" },
  { word: "achieve", meaning: "v. 达到；实现" },
  { word: "adapt", meaning: "v. 适应；改编" },
  { word: "admire", meaning: "v. 钦佩；欣赏" },
  { word: "admit", meaning: "v. 承认；准许进入" },
  { word: "advance", meaning: "n. 进步 v. 推进；前进" },
  { word: "advantage", meaning: "n. 优势；有利条件" },
  { word: "affect", meaning: "v. 影响；感动" },
  { word: "afford", meaning: "v. 负担得起；提供" },
  { word: "alternative", meaning: "n. 可供选择的事物 adj. 替代的" },
  { word: "ambitious", meaning: "adj. 有抱负的；雄心勃勃的" },
  { word: "amount", meaning: "n. 数量；总额 v. 总计" },
  { word: "analyze", meaning: "v. 分析" },
  { word: "announce", meaning: "v. 宣布；通知" },
  { word: "anxious", meaning: "adj. 焦虑的；渴望的" },
  { word: "apparent", meaning: "adj. 显而易见的；表面上的" },
  { word: "appeal", meaning: "n. 呼吁；吸引力 v. 呼吁" },
  { word: "appreciate", meaning: "v. 欣赏；感激；理解" },
  { word: "approach", meaning: "n. 方法；接近 v. 接近" },
  { word: "appropriate", meaning: "adj. 合适的；恰当的" },
  { word: "argue", meaning: "v. 争论；论证" },
  { word: "arrange", meaning: "v. 安排；整理" },
  { word: "assume", meaning: "v. 假定；承担" },
  { word: "attempt", meaning: "n. 尝试 v. 试图" },
  { word: "attract", meaning: "v. 吸引" },
  { word: "available", meaning: "adj. 可获得的；有空的" },
  { word: "average", meaning: "n. 平均数 adj. 平均的；普通的" },
  { word: "aware", meaning: "adj. 意识到的；知道的" },
  { word: "balance", meaning: "n. 平衡；余额 v. 保持平衡" },
  { word: "benefit", meaning: "n. 好处 v. 受益" },
  { word: "challenge", meaning: "n. 挑战 v. 向某人挑战" },
  { word: "circumstance", meaning: "n. 情况；环境" },
  { word: "claim", meaning: "v. 声称；索取 n. 声明" },
  { word: "combine", meaning: "v. 结合；联合" },
  { word: "comment", meaning: "n. 评论 v. 发表意见" },
  { word: "communicate", meaning: "v. 交流；传达" },
  { word: "compare", meaning: "v. 比较；对比" },
  { word: "compete", meaning: "v. 竞争；比赛" },
  { word: "concentrate", meaning: "v. 集中注意力；聚集" },
  { word: "concern", meaning: "n. 担忧；关心 v. 涉及" },
  { word: "conclude", meaning: "v. 得出结论；结束" },
  { word: "conduct", meaning: "v. 组织；实施 n. 行为" },
  { word: "confirm", meaning: "v. 确认；证实" },
  { word: "consequence", meaning: "n. 结果；后果" },
  { word: "consider", meaning: "v. 考虑；认为" },
  { word: "consist", meaning: "v. 由某物组成；在于" },
  { word: "constant", meaning: "adj. 持续的；不变的" },
  { word: "contribute", meaning: "v. 贡献；促成；投稿" },
  { word: "convenient", meaning: "adj. 方便的；便利的" },
  { word: "convince", meaning: "v. 使确信；说服" },
  { word: "curious", meaning: "adj. 好奇的；奇特的" },
  { word: "decrease", meaning: "v. 减少 n. 减少" },
  { word: "define", meaning: "v. 给某物下定义；界定" },
  { word: "demand", meaning: "n. 要求；需求 v. 要求" },
  { word: "demonstrate", meaning: "v. 证明；展示；示范" },
  { word: "depend", meaning: "v. 依靠；取决于" },
  { word: "determine", meaning: "v. 决定；确定" },
  { word: "develop", meaning: "v. 发展；培养；开发" },
  { word: "differ", meaning: "v. 不同；有分歧" },
  { word: "difficulty", meaning: "n. 困难；难题" },
  { word: "effective", meaning: "adj. 有效的；起作用的" },
  { word: "effort", meaning: "n. 努力；尝试" },
  { word: "encourage", meaning: "v. 鼓励；促进" },
  { word: "environment", meaning: "n. 环境；周围状况" },
  { word: "establish", meaning: "v. 建立；确立" },
  { word: "evaluate", meaning: "v. 评价；评估" },
  { word: "evidence", meaning: "n. 证据；迹象" },
  { word: "exist", meaning: "v. 存在；生存" },
  { word: "expand", meaning: "v. 扩大；扩展" },
  { word: "experience", meaning: "n. 经历；经验 v. 经历" },
  { word: "explain", meaning: "v. 解释；说明" },
  { word: "explore", meaning: "v. 探索；探究" },
  { word: "familiar", meaning: "adj. 熟悉的；常见的" },
  { word: "feature", meaning: "n. 特征；特色 v. 以某物为特色" },
  { word: "focus", meaning: "n. 焦点 v. 集中" },
  { word: "function", meaning: "n. 功能；函数 v. 运转" },
  { word: "generally", meaning: "adv. 通常；大体上" },
  { word: "hesitate", meaning: "v. 犹豫；迟疑" },
  { word: "identify", meaning: "v. 识别；确认" },
  { word: "ignore", meaning: "v. 忽视；不理睬" },
  { word: "impact", meaning: "n. 影响；冲击 v. 影响" },
  { word: "improve", meaning: "v. 改善；提高" },
  { word: "include", meaning: "v. 包括；包含" },
  { word: "indicate", meaning: "v. 表明；指出" },
  { word: "influence", meaning: "n. 影响 v. 影响" },
  { word: "insist", meaning: "v. 坚持；坚决要求" },
  { word: "inspire", meaning: "v. 激励；启发" },
  { word: "intend", meaning: "v. 打算；意指" },
  { word: "involve", meaning: "v. 涉及；使参与" },
  { word: "issue", meaning: "n. 问题；议题；期号" },
  { word: "maintain", meaning: "v. 维持；保养；坚持" },
  { word: "measure", meaning: "n. 措施；尺寸 v. 测量" },
  { word: "method", meaning: "n. 方法；办法" },
  { word: "motivate", meaning: "v. 激励；成为动机" },
  { word: "observe", meaning: "v. 观察；遵守；评论" },
  { word: "obtain", meaning: "v. 获得；得到" },
  { word: "occur", meaning: "v. 发生；出现" },
  { word: "opportunity", meaning: "n. 机会；时机" },
  { word: "ordinary", meaning: "adj. 普通的；平常的" },
  { word: "organize", meaning: "v. 组织；整理" },
  { word: "participate", meaning: "v. 参加；参与" },
  { word: "particular", meaning: "adj. 特定的；特别的；挑剔的" },
  { word: "perform", meaning: "v. 表演；执行；表现" },
  { word: "persuade", meaning: "v. 说服；劝说" },
  { word: "positive", meaning: "adj. 积极的；肯定的" },
  { word: "prevent", meaning: "v. 阻止；预防" },
  { word: "principle", meaning: "n. 原则；原理" },
  { word: "process", meaning: "n. 过程；流程 v. 加工" },
  { word: "produce", meaning: "v. 生产；产生 n. 农产品" },
  { word: "progress", meaning: "n. 进步；进展 v. 进步" },
  { word: "promote", meaning: "v. 促进；提升；宣传" },
  { word: "provide", meaning: "v. 提供；供应" },
  { word: "recognize", meaning: "v. 认出；承认；认可" },
  { word: "recommend", meaning: "v. 推荐；建议" },
  { word: "reduce", meaning: "v. 减少；降低" },
  { word: "reflect", meaning: "v. 反映；反射；思考" },
  { word: "relate", meaning: "v. 联系；讲述；理解" },
  { word: "require", meaning: "v. 要求；需要" },
  { word: "respond", meaning: "v. 回答；作出反应" },
  { word: "responsibility", meaning: "n. 责任；职责" },
  { word: "result", meaning: "n. 结果 v. 导致" },
  { word: "reveal", meaning: "v. 揭示；显示" },
  { word: "schedule", meaning: "n. 日程；计划 v. 安排" },
  { word: "significant", meaning: "adj. 重要的；显著的" },
  { word: "solution", meaning: "n. 解决办法；溶液" },
  { word: "source", meaning: "n. 来源；源头" },
  { word: "specific", meaning: "adj. 具体的；特定的" },
  { word: "strategy", meaning: "n. 策略；战略" },
  { word: "struggle", meaning: "v. 奋斗；挣扎 n. 斗争" },
  { word: "succeed", meaning: "v. 成功；继任" },
  { word: "suggest", meaning: "v. 建议；暗示" },
  { word: "support", meaning: "n. 支持 v. 支持；养活" },
  { word: "tend", meaning: "v. 往往会；趋向；照料" },
  { word: "theory", meaning: "n. 理论；学说" },
  { word: "tradition", meaning: "n. 传统；惯例" },
  { word: "treat", meaning: "v. 对待；治疗；款待" },
  { word: "value", meaning: "n. 价值；价值观 v. 重视" },
  { word: "vary", meaning: "v. 变化；使不同" },
  { word: "volunteer", meaning: "n. 志愿者 v. 自愿做" }
];

let ZHONGKAO_VOCABULARY = [
  { word: "able", meaning: "adj. 能够的；有能力的" },
  { word: "about", meaning: "prep. 关于 adv. 大约" },
  { word: "above", meaning: "prep. 在……上方 adj. 上面的" },
  { word: "accept", meaning: "v. 接受；同意" },
  { word: "accident", meaning: "n. 事故；意外" },
  { word: "across", meaning: "prep. 穿过；在对面" },
  { word: "activity", meaning: "n. 活动" },
  { word: "advice", meaning: "n. 建议；忠告" },
  { word: "afraid", meaning: "adj. 害怕的；担心的" },
  { word: "agree", meaning: "v. 同意；赞成" },
  { word: "allow", meaning: "v. 允许；准许" },
  { word: "alone", meaning: "adj. 单独的 adv. 独自" },
  { word: "already", meaning: "adv. 已经" },
  { word: "although", meaning: "conj. 虽然；尽管" },
  { word: "amazing", meaning: "adj. 令人惊奇的" },
  { word: "among", meaning: "prep. 在……之中" },
  { word: "answer", meaning: "n. 答案 v. 回答" },
  { word: "anything", meaning: "pron. 任何事物" },
  { word: "arrive", meaning: "v. 到达" },
  { word: "attention", meaning: "n. 注意；关注" },
  { word: "autumn", meaning: "n. 秋天" },
  { word: "beautiful", meaning: "adj. 美丽的" },
  { word: "because", meaning: "conj. 因为" },
  { word: "become", meaning: "v. 变成；成为" },
  { word: "believe", meaning: "v. 相信；认为" },
  { word: "borrow", meaning: "v. 借入" },
  { word: "brave", meaning: "adj. 勇敢的" },
  { word: "break", meaning: "v. 打破；休息 n. 间歇" },
  { word: "bridge", meaning: "n. 桥" },
  { word: "bright", meaning: "adj. 明亮的；聪明的" },
  { word: "build", meaning: "v. 建造；建立" },
  { word: "careful", meaning: "adj. 小心的；仔细的" },
  { word: "carry", meaning: "v. 携带；搬运" },
  { word: "certain", meaning: "adj. 确定的；某个" },
  { word: "change", meaning: "n. 变化 v. 改变" },
  { word: "choose", meaning: "v. 选择" },
  { word: "clear", meaning: "adj. 清楚的；晴朗的" },
  { word: "clever", meaning: "adj. 聪明的" },
  { word: "collect", meaning: "v. 收集；收藏" },
  { word: "comfortable", meaning: "adj. 舒适的" },
  { word: "common", meaning: "adj. 常见的；共同的" },
  { word: "complete", meaning: "adj. 完整的 v. 完成" },
  { word: "continue", meaning: "v. 继续" },
  { word: "correct", meaning: "adj. 正确的 v. 改正" },
  { word: "country", meaning: "n. 国家；乡村" },
  { word: "culture", meaning: "n. 文化" },
  { word: "dangerous", meaning: "adj. 危险的" },
  { word: "decide", meaning: "v. 决定" },
  { word: "delicious", meaning: "adj. 美味的" },
  { word: "different", meaning: "adj. 不同的" },
  { word: "difficult", meaning: "adj. 困难的" },
  { word: "discover", meaning: "v. 发现" },
  { word: "during", meaning: "prep. 在……期间" },
  { word: "earth", meaning: "n. 地球；泥土" },
  { word: "education", meaning: "n. 教育" },
  { word: "enough", meaning: "adj. 足够的 adv. 足够地" },
  { word: "environment", meaning: "n. 环境" },
  { word: "especially", meaning: "adv. 尤其；特别" },
  { word: "example", meaning: "n. 例子；榜样" },
  { word: "excited", meaning: "adj. 兴奋的" },
  { word: "exercise", meaning: "n. 练习；运动 v. 锻炼" },
  { word: "experience", meaning: "n. 经历；经验 v. 经历" },
  { word: "explain", meaning: "v. 解释；说明" },
  { word: "famous", meaning: "adj. 著名的" },
  { word: "festival", meaning: "n. 节日" },
  { word: "finish", meaning: "v. 完成；结束" },
  { word: "foreign", meaning: "adj. 外国的" },
  { word: "forget", meaning: "v. 忘记" },
  { word: "friendly", meaning: "adj. 友好的" },
  { word: "future", meaning: "n. 将来 adj. 将来的" },
  { word: "happen", meaning: "v. 发生" },
  { word: "healthy", meaning: "adj. 健康的" },
  { word: "helpful", meaning: "adj. 有帮助的" },
  { word: "history", meaning: "n. 历史" },
  { word: "important", meaning: "adj. 重要的" },
  { word: "improve", meaning: "v. 改进；提高" },
  { word: "include", meaning: "v. 包括；包含" },
  { word: "instead", meaning: "adv. 代替；反而" },
  { word: "interest", meaning: "n. 兴趣 v. 使感兴趣" },
  { word: "introduce", meaning: "v. 介绍；引入" },
  { word: "invite", meaning: "v. 邀请" },
  { word: "journey", meaning: "n. 旅行；旅程" },
  { word: "knowledge", meaning: "n. 知识" },
  { word: "language", meaning: "n. 语言" },
  { word: "learn", meaning: "v. 学习；得知" },
  { word: "leave", meaning: "v. 离开；留下" },
  { word: "listen", meaning: "v. 听；倾听" },
  { word: "message", meaning: "n. 信息；消息" },
  { word: "mistake", meaning: "n. 错误 v. 误解" },
  { word: "modern", meaning: "adj. 现代的" },
  { word: "natural", meaning: "adj. 自然的；天然的" },
  { word: "necessary", meaning: "adj. 必要的" },
  { word: "notice", meaning: "n. 通知 v. 注意到" },
  { word: "opinion", meaning: "n. 意见；看法" },
  { word: "possible", meaning: "adj. 可能的" },
  { word: "practice", meaning: "n. 练习 v. 练习" },
  { word: "prepare", meaning: "v. 准备" },
  { word: "protect", meaning: "v. 保护" },
  { word: "provide", meaning: "v. 提供" },
  { word: "question", meaning: "n. 问题 v. 询问" },
  { word: "remember", meaning: "v. 记得；记住" },
  { word: "return", meaning: "v. 返回；归还" },
  { word: "special", meaning: "adj. 特别的；特殊的" },
  { word: "successful", meaning: "adj. 成功的" },
  { word: "together", meaning: "adv. 一起；共同" },
  { word: "understand", meaning: "v. 理解；明白" },
  { word: "useful", meaning: "adj. 有用的" },
  { word: "without", meaning: "prep. 没有；不使用" },
  { word: "wonderful", meaning: "adj. 精彩的；极好的" }
];
